GapPolicy/Controllers/ClientsController.cs
using GapPolicyBUSINESS;
using GapPolicyDAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace GapPolicy.Controllers
{
    [Authorize]
    public class ClientsController : Controller
    {
        ClientBusiness clientBus = new ClientBusiness();
        // GET: Clients
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetClients()
        {
            return Json(clientBus.GetClients(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeleteClients(string Identification)
        {
            return Json(clientBus.DeleteClients(Identification));
        }

        [HttpPost]
        public ActionResult InsertClients(Client client)
        {
            client.ModificationUser = User.Identity.Name;
            return Json(clientBus.InsertClients(client));
        }

        [HttpPost]
        public ActionResult UpdateClients(Client client)
        {
            client.ModificationUser = User.Identity.Name;
            return Json(clientBus.UpdateClients(client));
        }

        [HttpGet]
        public ActionResult GetClientsIdentification(string Identification)
        {
            return Json(clientBus.GetClientIdentification(Identification), JsonRequestBehavior.AllowGet);
        }
    }
}

GapPolicy/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

GapPolicy/Controllers/LoginController.cs
using GapPolicyBUSINESS;
using GapPolicyDAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace GapPolicy.Controllers
{
    public class LoginController : Controller
    {
        LoginBusiness bus = new LoginBusiness();
        // GET: Login
        public ActionResult Index(string message=null)
        {
            ViewBag.Message = message;
            return View();
        }

        public ActionResult Validate(Login login)
        {

            Login credentials;
            if (!string.IsNullOrEmpty(login.Identification) && !string.IsNullOrEmpty(login.Password))
            {
                credentials = bus.GetCredentials(login).FirstOrDefault();
                if (credentials != null)
                {
                    FormsAuthentication.SetAuthCookie(credentials.Identification, true);                   
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("Index", new { message = "User not exist." });
                }
            }
            else
            {
                return RedirectToAction("Index", new { message = "Credential is empty." });
            }
        }

        [Authorize]
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }
    }
}

GapPolicy/Controllers/PolicyController.cs
using GapPolicyBUSINESS;
using GapPolicyDAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GapPolicy.Controllers
{
    [Authorize]
    public class PolicyController : Controller
    {
        PolicyBusiness policytBus = new PolicyBusiness();
        // GET: Policy
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetPolicy()
        {
            return Json(policytBus.GetPolicy(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeletePolicy(int Id)
        {
            return Json(policytBus.DeletePolicy(Id, User.Identity.Name));
        }

        [HttpPost]
        public ActionResult InsertPolicy(Policy policy)
        {
            policy.ModificationUser = User.Identity.Name;
            return Json(policytBus.InsertPolicy(policy));
        }

        [HttpPost]
        public ActionResult UpdatePolicy(Policy policy)
        {
            policy.ModificationUser = User.Identity.Name;
            return Json(policytBus.UpdatePolicy(policy));
        }

        [HttpGet]
        public ActionResult GetPolicyId(string Id)
        {
            return Json(policytBus.GetPolicyId(Id), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetPolicyType()
        {
            return Json(policytBus.GetPolicyTypes(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetClients()
        {
            return Json(policytBus.GetClients(), JsonRequestBehavior.AllowGet);
        }
    }
}

GapPolicy/Controllers/PolicyTypeController.cs
using GapPolicyBUSINESS;
using GapPolicyDAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GapPolicy.Controllers
{
    [Authorize]
    public class PolicyTypeController : Controller
    {

        PolicyTypeBusiness policyBus = new PolicyTypeBusiness();
        // GET: PolicyType
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetPolicyType()
        {
            return Json(policyBus.GetPolicyType(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeletePolicyType(int Id)
        {
            return Json(policyBus.DeletePolicyType(Id));
        }

        [HttpPost]
        public ActionResult InsertPolicyType(PolicyCatalog policy)
        {
            policy.ModificationUser = User.Identity.Name;
            return Json(policyBus.InsertPolicyType(policy));
        }

        [HttpPost]
        public ActionResult UpdatePolicyType(PolicyCatalog policy)
        {
            policy.ModificationUser = User.Identity.Name;
            return Json(policyBus.UpdatePolicyType(policy));
        }

        [HttpGet]
        public ActionResult GetPolicyTypeIdentification(int Id)
        {
            return Json(policyBus.GetPolicyTypeId(Id), JsonRequestBehavior.AllowGet);
        }
    }
}

GapPolicy/Views/Clients/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Clients Manager</h2>
<div id="tabs-clients">
    <ul class="nav nav-tabs">
        <li><a href="#fisrtTab">Details</a></li>
        <li><a href="#secondTab">Create</a></li>
    </ul>
    <div id="fisrtTab">
        <table id="tableClientInfo" class="table table-striped dt-responsive nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Identification</th>
                    <th>Name</th>
                    <th>PhoneNumber</th>
                    <th>Mail</th>
                    <th>Address</th>
                    <th>Controls</th>
                </tr>
            </thead>
            <tbody id="tblClientInfo"></tbody>
        </table>
    </div>
    <div id="secondTab">
        <div>
            <form class="form-panel">
                <div class="form-group">
                    <label>Identification:</label>
                    <input type="text" class="form-control" id="txtClientIdentification">
                </div>
                <div class="form-group">
                    <label>Name:</label>
                    <input type="text" class="form-control" id="txtClientName">
                </div>
                <div class="form-group">
                    <label>PhoneNumber:</label>
                    <input type="text" class="form-control" id="txtClientPhoneNumber">
                </div>
                <div class="form-group">
                    <label>Mail:</label>
                    <input type="text" class="form-control" id="txtClientMail">
                </div>
                <div class="form-group">
                    <label>Address:</label>
                    <input type="text" class="form-control" id="txtClientAddress">
                </div>
                <button type="submit" class="btn btn-primary" onclick="insertClient()">Save</button>
            </form>
        </div>
    </div>
</div>

@*Modals Windows*@
<div class="modal fade" Id="modalClient" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal">x</button>
            <h4>Client update information</h4>
            <div class="modal-body">
                <div>
                    <form class="form-panel">
                        <div class="form-group">
                            <label>Identification:</label>
                            <input type="text" class="form-control" id="txtClientIdentificationUpdate" readonly>
                        </div>
                        <div class="form-group">
                            <label>Name:</label>
                            <input type="text" class="form-control" id="txtClientNameUpdate">
                        </div>
                        <div class="form-group">
                            <label>PhoneNumber:</label>
                            <input type="text" class="form-control" id="txtClientPhoneNumberUpdate">
                        </div>
                        <div class="form-group">
                            <label>Mail:</label>
                            <input type="text" class="form-control" id="txtClientMailUpdate">
                        </div>
                        <div class="form-group">
                            <label>Address:</label>
                            <input type="text" class="form-control" id="txtClientAddressUpdate">
                        </div>                      
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <div class="row">
                        <button type="submit" class="btn btn-primary" onclick="updateClient()">Save</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/Project/Clients.js"></script>

GapPolicy/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>GROWTH ACCELERATION PARTNERS</h1>
    <p class="lead">Test insurance policies.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>CLIENTS</h2>
        <p>
            View and manage all details related to company customers.
        </p>
        <p><a class="btn btn-primary" href="/Clients">go &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>POLICY</h2>
        <p>
            View and manage the policy portfolio that the company has..
        </p>
        <p><a class="btn btn-primary" href="/Policy">go &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>POLICY TYPE</h2>
        <p>
            View and manage the different types of policies that the company has at the service of customers.
        </p>
        <p><a class="btn btn-primary" href="/PolicyType">go &raquo;</a></p>
    </div>
</div>

GapPolicy/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Access Control</h2>
<div>
    <form class="form-panel" action="~/Login/Validate">
        @{
            if (!string.IsNullOrEmpty(ViewBag.Message)) {
                <div class="alert alert-danger">@ViewBag.Message</div>
            }
        }
        <div class="form-group">
            <label>User Id (Identification):</label>
            <input type="text" class="form-control" id="txtLoginIdentification" name="Identification">
        </div>
        <div class="form-group">
            <label>Passowrd:</label>
            <input type="password" class="form-control" id="txtLoginPassword" name="Password">
        </div>        
        <button id="btnLogin" type="submit" class="btn btn-primary">Login</button>
    </form>
</div>

GapPolicy/Views/Policy/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Policy Manager</h2>

<div id="tabs-policy">
    <ul class="nav nav-tabs">
        <li><a href="#fisrtTab">Details</a></li>
        <li><a href="#secondTab">Create</a></li>
    </ul>
    <div id="fisrtTab">
        <table id="tablePolicyInfo" class="table table-striped dt-responsive nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Client</th>
                    <th>Type</th>
                    <th>Percentage</th>
                    <th>StartDate</th>
                    <th>EndDate</th>
                    <th>Period</th>
                    <th>Cost</th>
                    <th>RiskType</th>
                    <th>Status</th>
                    <th>Controls</th>
                </tr>
            </thead>
            <tbody id="tblPolicyInfo"></tbody>
        </table>
    </div>
    <div id="secondTab">
        <div>
            <form class="form-panel">
                <div class="form-group">
                    <label>Client:</label>
                    <select name="clients" id="txtPolicyClient">
                        <option value="-1">--- Seleccione --</option>
                    </select>
                </div>

                <div class="form-group">
                    <label>Type:</label>
                    <select name="types" id="txtPolicyType">
                        <option value="-1">--- Seleccione --</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Percentage:</label>
                    <input type="text" class="form-control" id="txtPolicyPercentage">
                </div>
                <div class="form-group">
                    <label>StartDate:</label>
                    <input type="text" class="form-control" id="txtPolicyStartDate" readonly>
                </div>
                <div class="form-group">
                    <label>EndDate:</label>
                    <input type="text" class="form-control" id="txtPolicyEndDate" readonly>
                </div>
                <div class="form-group">
                    <label>Period:</label>
                    <input type="text" class="form-control" id="txtPolicyPeriod">
                </div>
                <div class="form-group">
                    <label>Cost:</label>
                    <input type="text" class="form-control" id="txtPolicyCost">
                </div>
                <div class="form-group">
                    <label>RiskType:</label>
                    <select name="types" id="txtPolicyRiskType">
                        <option value="low">low</option>
                        <option value="medium">medium</option>
                        <option value="medium-high">medium-high</option>
                        <option value="high">high</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary" onclick="insertPolicy()">Save</button>
            </form>
        </div>
    </div>
</div>

@*Modals Windows*@
<div class="modal fade" Id="modalPolicy" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal">x</button>
            <h4>Policy update information</h4>
            <div class="modal-body">
                <div>
                    <form class="form-panel">
                        <div class="form-group">
                            <label>Id:</label>
                            <input type="text" class="form-control" id="txtPolicyIdUp" readonly>
                        </div>
                        <div class="form-group">
                            <label>Client:</label>
                            <select name="clientsUP" id="txtPolicyClientUP">
                                <option value="-1">--- Seleccione --</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Type:</label>
                            <select name="types" id="txtPolicyTypeUP">
                                <option value="-1">--- Seleccione --</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Percentage:</label>
                            <input type="text" class="form-control" id="txtPolicyPercentageUP">
                        </div>
                        <div class="form-group">
                            <label>StartDate:</label>
                            <input type="text" class="form-control" id="txtPolicyStartDateUp">
                        </div>
                        <div class="form-group">
                            <label>EndDate:</label>
                            <input type="text" class="form-control" id="txtPolicyEndDateUp">
                        </div>
                        <div class="form-group">
                            <label>Period:</label>
                            <input type="text" class="form-control" id="txtPolicyPeriodUp">
                        </div>
                        <div class="form-group">
                            <label>Cost:</label>
                            <input type="text" class="form-control" id="txtPolicyCostUp">
                        </div>
                        <div class="form-group">
                            <label>RiskType:</label>
                            <select name="types" id="txtPolicyRiskTypeUp">
                                <option value="low">low</option>
                                <option value="medium">medium</option>
                                <option value="medium-high">medium-high</option>
                                <option value="high">high</option>
                            </select>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <button type="submit" class="btn btn-primary" onclick="updatePolicy()">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/Project/Policy.js"></script>

GapPolicy/Views/PolicyType/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Policy Type Manager</h2>
<div id="tabs-policy-type">
    <ul class="nav nav-tabs">
        <li><a href="#fisrtTab">Details</a></li>
        <li><a href="#secondTab">Create</a></li>
    </ul>
    <div id="fisrtTab">
        <table id="tablePolicyTypeInfo" class="table table-striped dt-responsive nowrap">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Type</th>
                    <th>Description</th>
                    <th>Controls</th>
                </tr>
            </thead>
            <tbody id="tblPolicyTypeInfo"></tbody>
        </table>
    </div>
    <div id="secondTab">
        <div>
            <form class="form-panel">
                <div class="form-group">
                    <label>Type:</label>
                    <input type="text" class="form-control" id="txtPolicyTypeType">
                </div>
                <div class="form-group">
                    <label>Description:</label>
                    <input type="text" class="form-control" id="txtPolicyTypeDescription">
                </div>
                <button type="submit" class="btn btn-primary" onclick="insertPolicyType()">Save</button>
            </form>
        </div>
    </div>
</div>

@*Modals Windows*@
<div class="modal fade" Id="modalPolicyType" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal">x</button>
            <h4>Policy type update information</h4>
            <div class="modal-body">
                <div>
                    <form class="form-panel">
                        <div class="form-group">
                            <label>Id:</label>
                            <input type="text" class="form-control" id="txtPolicyTypeIdUp" readonly>
                        </div>
                        <div class="form-group">
                            <label>Type:</label>
                            <input type="text" class="form-control" id="txtPolicyTypeTypeUp">
                        </div>
                        <div class="form-group">
                            <label>Description:</label>
                            <input type="text" class="form-control" id="txtPolicyTypeDescriptionUp">
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <button type="submit" class="btn btn-primary" onclick="updatePolicyType()">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/Project/PolicyType.js"></script>

GapPolicy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Images/IconGap.png" type="image/png" />
    <title>Policy GAP</title>
    @*CSS*@
    <link href="~/Styles/Frameworks/jquery-ui.css" rel="stylesheet" />
    <link href="~/Styles/Frameworks/bootstrap.css" rel="stylesheet" />
    <link href="~/Scripts/FrameWorks/DataTables/datatables.css" rel="stylesheet" />
    <link href="~/Styles/Project/Site.css" rel="stylesheet" />

    @*Scripts*@
    <script src="~/Scripts/FrameWorks/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/FrameWorks/jquery-ui.min.js"></script>
    <script src="~/Scripts/FrameWorks/bootstrap.min.js"></script>
    <script src="~/Scripts/FrameWorks/DataTables/datatables.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h4>
                    <img src="~/Images/IconGap.png" /> @Html.ActionLink("Policy Control - GAP", "Index", "home")
                </h4>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Clients", "Index", "Clients")</li>
                    <li>@Html.ActionLink("Policys", "Index", "Policy")</li>
                    <li>@Html.ActionLink("Policy Types", "Index", "PolicyType")</li>
                    @{
                        if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Log Out", "LogOut", "Login")</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&#64; Policy Gap Control - 2020</p>
        </footer>
    </div>
</body>
</html>